import type { JobRequest, JobStatus, VoiceOption } from './contracts'
import { createQueuedJob } from '../jobs/queue'

export const voiceCatalog: VoiceOption[] = [
  // ── PT-BR — Feminino ──────────────────────────────────────────────────────
  {
    id: 'pt-br-clara',
    label: 'Clara',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Didática natural',
    description: 'Voz feminina adulta, calorosa e clara. Ideal para tutoriais e cursos online.',
    emotions: ['neutro', 'calmo', 'feliz'],
    useCases: ['tutorial', 'institucional', 'audiolibro'],
  },
  {
    id: 'pt-br-ana',
    label: 'Ana',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Suave e acolhedora',
    description: 'Voz feminina suave, com ritmo tranquilo e tom caloroso. Perfeita para conteúdos educativos.',
    emotions: ['neutro', 'calmo', 'feliz'],
    useCases: ['tutorial', 'institucional'],
  },
  {
    id: 'pt-br-beatriz',
    label: 'Beatriz',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Tranquila e profissional',
    description: 'Voz feminina adulta, profissional e serena. Ótima para onboarding e apresentações corporativas.',
    emotions: ['neutro', 'calmo', 'sério'],
    useCases: ['tutorial', 'institucional', 'anúncio'],
  },
  {
    id: 'pt-br-camila',
    label: 'Camila',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'jovem',
    style: 'Jovial e natural',
    description: 'Voz feminina jovem, descontraída e natural. Ideal para conteúdo em redes sociais e tutoriais leves.',
    emotions: ['neutro', 'feliz', 'animado'],
    useCases: ['tutorial', 'entretenimento', 'anúncio'],
  },
  {
    id: 'pt-br-diana',
    label: 'Diana',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Narrativa envolvente',
    description: 'Voz feminina com entonação envolvente e ritmo pausado. Perfeita para narração e audiolibros.',
    emotions: ['neutro', 'calmo', 'dramático', 'sério'],
    useCases: ['narrativa', 'audiolibro', 'documentário'],
  },
  {
    id: 'pt-br-fernanda',
    label: 'Fernanda',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Clara e motivadora',
    description: 'Voz feminina inspiradora, com energia positiva e dicção nítida. Ideal para cursos e treinamentos.',
    emotions: ['neutro', 'feliz', 'animado', 'calmo'],
    useCases: ['tutorial', 'institucional', 'anúncio'],
  },
  {
    id: 'pt-br-helena',
    label: 'Helena',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'idoso',
    style: 'Sábia e serena',
    description: 'Voz feminina madura, serena e confiável. Transmite experiência e autoridade de forma gentil.',
    emotions: ['neutro', 'calmo', 'sério'],
    useCases: ['institucional', 'documentário', 'narrativa', 'audiolibro'],
  },
  {
    id: 'pt-br-isabela',
    label: 'Isabela',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'jovem',
    style: 'Amigável e informal',
    description: 'Voz feminina jovem e amigável, com tom informal e próximo ao ouvinte.',
    emotions: ['neutro', 'feliz', 'animado', 'calmo'],
    useCases: ['tutorial', 'entretenimento', 'anúncio'],
  },
  {
    id: 'pt-br-julia',
    label: 'Júlia',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Precisa e técnica',
    description: 'Voz feminina com dicção muito clara, indicada para conteúdo técnico e documentação.',
    emotions: ['neutro', 'sério', 'calmo'],
    useCases: ['tutorial', 'institucional', 'documentário'],
  },
  {
    id: 'pt-br-livia',
    label: 'Lívia',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Melodiosa e cativante',
    description: 'Voz feminina com entonação melodiosa, boa para conteúdo criativo e storytelling.',
    emotions: ['neutro', 'feliz', 'calmo', 'animado'],
    useCases: ['narrativa', 'entretenimento', 'audiolibro'],
  },
  {
    id: 'pt-br-marina',
    label: 'Marina',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'feminino',
    ageGroup: 'adulto',
    style: 'Dinâmica e expressiva',
    description: 'Voz feminina com grande expressividade. Adapta-se bem a diferentes contextos e emoções.',
    emotions: ['neutro', 'feliz', 'triste', 'animado', 'sério'],
    useCases: ['tutorial', 'anúncio', 'narrativa', 'entretenimento'],
  },
  // ── PT-BR — Masculino ─────────────────────────────────────────────────────
  {
    id: 'pt-br-rafael',
    label: 'Rafael',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'masculino',
    ageGroup: 'adulto',
    style: 'Narrador técnico',
    description: 'Voz masculina clara e confiante. Indicada para documentações técnicas e tutoriais.',
    emotions: ['neutro', 'sério', 'calmo'],
    useCases: ['tutorial', 'institucional', 'documentário'],
  },
  {
    id: 'pt-br-marcos',
    label: 'Marcos',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'masculino',
    ageGroup: 'adulto',
    style: 'Grave e profissional',
    description: 'Voz masculina grave, tranquila e profissional. Ideal para conteúdo corporativo e institucional.',
    emotions: ['neutro', 'sério', 'calmo'],
    useCases: ['institucional', 'anúncio', 'documentário'],
  },
  {
    id: 'pt-br-diego',
    label: 'Diego',
    locale: 'pt-BR',
    language: 'pt-BR',
    gender: 'masculino',
    ageGroup: 'jovem',
    style: 'Energético e jovem',
    description: 'Voz masculina jovem, com energia e entusiasmo. Ótima para vídeos de entretenimento e redes sociais.',
    emotions: ['neutro', 'feliz', 'animado'],
    useCases: ['entretenimento', 'anúncio', 'tutorial'],
  },
  // ── EN-US — Female ────────────────────────────────────────────────────────
  {
    id: 'en-us-ava',
    label: 'Ava',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'American',
    style: 'Friendly instructional',
    description: 'Clear, warm American female voice. Great for e-learning and product tutorials.',
    emotions: ['neutro', 'feliz', 'calmo'],
    useCases: ['tutorial', 'institucional', 'anúncio'],
  },
  {
    id: 'en-us-emily',
    label: 'Emily',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'jovem',
    accent: 'American – West Coast',
    style: 'Upbeat and modern',
    description: 'Young American female voice, energetic and relatable. Perfect for social media and short-form content.',
    emotions: ['neutro', 'feliz', 'animado', 'ansioso'],
    useCases: ['anúncio', 'entretenimento', 'tutorial'],
  },
  {
    id: 'en-us-rachel',
    label: 'Rachel',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'American – Midwest',
    style: 'Calm and authoritative',
    description: 'Balanced American female voice with neutral Midwest accent. Versatile for any formal content.',
    emotions: ['neutro', 'calmo', 'sério'],
    useCases: ['institucional', 'documentário', 'notícias'],
  },
  {
    id: 'en-us-patricia',
    label: 'Patricia',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'idoso',
    accent: 'American',
    style: 'Warm and wise',
    description: 'Mature American female voice, wise and reassuring. Excellent for storytelling and audiobooks.',
    emotions: ['neutro', 'calmo', 'triste', 'feliz'],
    useCases: ['audiolibro', 'narrativa', 'documentário'],
  },
  {
    id: 'en-us-jessica',
    label: 'Jessica',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'American – Southern',
    style: 'Conversational and warm',
    description: 'Southern American female voice, charming and conversational. Great for brand storytelling.',
    emotions: ['neutro', 'feliz', 'calmo', 'animado'],
    useCases: ['anúncio', 'narrativa', 'entretenimento'],
  },
  {
    id: 'en-us-sophia',
    label: 'Sophia',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'American – East Coast',
    style: 'Dramatic and expressive',
    description: 'Highly expressive American female voice. Supports a wide emotional range for cinematic narration.',
    emotions: ['neutro', 'dramático', 'triste', 'medo', 'surpreso', 'ansioso', 'feliz'],
    useCases: ['dramático', 'narrativa', 'audiolibro'],
  },
  {
    id: 'en-us-whispering-grace',
    label: 'Grace (Whisper)',
    locale: 'en-US',
    language: 'en-US',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'American',
    style: 'Soft whisper',
    description: 'Soft whispering American female voice. Ideal for ASMR-style content, meditation, and intimate narration.',
    emotions: ['sussurrando', 'calmo', 'neutro'],
    useCases: ['narrativa', 'entretenimento', 'audiolibro'],
  },
  // ── EN-US — Male ─────────────────────────────────────────────────────────
  {
    id: 'en-us-james',
    label: 'James',
    locale: 'en-US',
    language: 'en-US',
    gender: 'masculino',
    ageGroup: 'adulto',
    accent: 'American',
    style: 'Deep and professional',
    description: 'Deep, authoritative American male voice. Perfect for corporate presentations and news narration.',
    emotions: ['neutro', 'sério', 'calmo'],
    useCases: ['institucional', 'notícias', 'documentário'],
  },
  {
    id: 'en-us-tyler',
    label: 'Tyler',
    locale: 'en-US',
    language: 'en-US',
    gender: 'masculino',
    ageGroup: 'jovem',
    accent: 'American – West Coast',
    style: 'Casual and energetic',
    description: 'Young American male voice with a casual, tech-savvy feel. Great for tutorials and vlogs.',
    emotions: ['neutro', 'feliz', 'animado', 'surpreso'],
    useCases: ['tutorial', 'entretenimento', 'anúncio'],
  },
  {
    id: 'en-us-robert',
    label: 'Robert',
    locale: 'en-US',
    language: 'en-US',
    gender: 'masculino',
    ageGroup: 'idoso',
    accent: 'American – Southern',
    style: 'Gravelly and storytelling',
    description: 'Older American male voice with a rich, gravelly quality. Outstanding for documentary and long-form narration.',
    emotions: ['neutro', 'calmo', 'sério', 'triste', 'dramático'],
    useCases: ['documentário', 'narrativa', 'audiolibro'],
  },
  {
    id: 'en-us-marcus',
    label: 'Marcus',
    locale: 'en-US',
    language: 'en-US',
    gender: 'masculino',
    ageGroup: 'adulto',
    accent: 'American – Midwest',
    style: 'Dramatic and cinematic',
    description: 'Powerful American male voice with a wide emotional palette. Built for cinematic and dramatic storytelling.',
    emotions: ['neutro', 'dramático', 'sério', 'medo', 'ansioso', 'triste', 'surpreso', 'suspeitando'],
    useCases: ['dramático', 'narrativa', 'anúncio'],
  },
  {
    id: 'en-us-charlie',
    label: 'Charlie',
    locale: 'en-US',
    language: 'en-US',
    gender: 'masculino',
    ageGroup: 'adulto',
    accent: 'American',
    style: 'Friendly and approachable',
    description: 'Friendly all-purpose American male voice. Versatile for explainer videos and instructional content.',
    emotions: ['neutro', 'feliz', 'calmo', 'animado'],
    useCases: ['tutorial', 'institucional', 'anúncio'],
  },
  // ── EN-GB — Female ────────────────────────────────────────────────────────
  {
    id: 'en-gb-olivia',
    label: 'Olivia',
    locale: 'en-GB',
    language: 'en-GB',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'British – RP',
    style: 'Elegant and articulate',
    description: 'Received Pronunciation British female voice, elegant and precise. Excellent for high-end brand content.',
    emotions: ['neutro', 'calmo', 'sério', 'irônico'],
    useCases: ['institucional', 'anúncio', 'documentário', 'audiolibro'],
  },
  {
    id: 'en-gb-charlotte',
    label: 'Charlotte',
    locale: 'en-GB',
    language: 'en-GB',
    gender: 'feminino',
    ageGroup: 'jovem',
    accent: 'British – London',
    style: 'Lively and modern',
    description: 'Contemporary British female voice with a youthful London accent. Fun and engaging.',
    emotions: ['neutro', 'feliz', 'animado', 'surpreso'],
    useCases: ['entretenimento', 'anúncio', 'tutorial'],
  },
  // ── EN-GB — Male ─────────────────────────────────────────────────────────
  {
    id: 'en-gb-henry',
    label: 'Henry',
    locale: 'en-GB',
    language: 'en-GB',
    gender: 'masculino',
    ageGroup: 'adulto',
    accent: 'British – RP',
    style: 'Classic and authoritative',
    description: 'Classic British RP male voice. Commands attention; ideal for documentaries and formal narration.',
    emotions: ['neutro', 'sério', 'calmo', 'dramático'],
    useCases: ['documentário', 'institucional', 'narrativa'],
  },
  {
    id: 'en-gb-george',
    label: 'George',
    locale: 'en-GB',
    language: 'en-GB',
    gender: 'masculino',
    ageGroup: 'idoso',
    accent: 'British – Northern',
    style: 'Warm and seasoned',
    description: 'Older British male voice with a warm Northern English accent. Perfect for long-form storytelling.',
    emotions: ['neutro', 'calmo', 'triste', 'sério'],
    useCases: ['audiolibro', 'narrativa', 'documentário'],
  },
  // ── EN-AU — Female / Male ─────────────────────────────────────────────────
  {
    id: 'en-au-sophie',
    label: 'Sophie',
    locale: 'en-AU',
    language: 'en-AU',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'Australian',
    style: 'Bright and friendly',
    description: 'Bright Australian female voice, friendly and conversational. Great for lifestyle and wellness content.',
    emotions: ['neutro', 'feliz', 'calmo', 'animado'],
    useCases: ['tutorial', 'entretenimento', 'anúncio'],
  },
  {
    id: 'en-au-jack',
    label: 'Jack',
    locale: 'en-AU',
    language: 'en-AU',
    gender: 'masculino',
    ageGroup: 'adulto',
    accent: 'Australian',
    style: 'Laid-back and authentic',
    description: 'Relaxed Australian male voice. Authentic and down-to-earth, great for brand storytelling.',
    emotions: ['neutro', 'calmo', 'feliz'],
    useCases: ['anúncio', 'entretenimento', 'narrativa'],
  },
  // ── EN-IN — Female / Male ─────────────────────────────────────────────────
  {
    id: 'en-in-priya',
    label: 'Priya',
    locale: 'en-IN',
    language: 'en-IN',
    gender: 'feminino',
    ageGroup: 'adulto',
    accent: 'Indian English',
    style: 'Clear and melodic',
    description: 'Clear Indian English female voice with a melodic quality. Excellent for tech tutorials and education.',
    emotions: ['neutro', 'calmo', 'feliz', 'sério'],
    useCases: ['tutorial', 'institucional', 'documentário'],
  },
  {
    id: 'en-in-arjun',
    label: 'Arjun',
    locale: 'en-IN',
    language: 'en-IN',
    gender: 'masculino',
    ageGroup: 'adulto',
    accent: 'Indian English',
    style: 'Confident and expressive',
    description: 'Confident Indian English male voice, expressive and engaging. Great for tech and startup content.',
    emotions: ['neutro', 'feliz', 'animado', 'sério'],
    useCases: ['tutorial', 'anúncio', 'institucional'],
  },
]

function createJobId(prefix: string): string {
  return `${prefix}-${Math.random().toString(36).slice(2, 9)}`
}

export function requestJob(type: JobRequest['type'], input: JobRequest['input']): JobStatus {
  const request: JobRequest = {
    id: createJobId(type),
    type,
    input,
    createdAt: new Date().toISOString(),
  }

  return createQueuedJob(request)
}
